version: '3.1'
volumes:
  s3dexp-dbdata:
    external: true

services:
  adminer:
    image: adminer
    container_name: s3dexp-adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

  db:
    image: mysql
    container_name: s3dexp-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: exp
    volumes:
      - s3dexp-dbdata:/var/lib/mysql
