
build:
	docker build -t registry.cmusatyalab.org/zf/diamond-public-registry/kinetic:arm .

push:
	docker push registry.cmusatyalab.org/zf/diamond-public-registry/kinetic:arm

pull:
	docker pull registry.cmusatyalab.org/zf/diamond-public-registry/kinetic:arm