"""Add hostname column

Revision ID: 32f572f83825
Revises: ec860df076ec
Create Date: 2019-09-08 16:26:34.901698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f572f83825'
down_revision = 'ec860df076ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EurekaExp', sa.Column('hostname', sa.String(length=1024), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EurekaExp', 'hostname')
    # ### end Alembic commands ###
