"""Add disk column to DiskReadProfile

Revision ID: 37fe9a92ef6e
Revises: b81041dfae9a
Create Date: 2019-08-13 20:50:57.328585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37fe9a92ef6e'
down_revision = 'b81041dfae9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DiskReadProfile', sa.Column('disk', sa.String(length=20), nullable=True))
    op.drop_column('DiskReadProfile', 'rand_read_ms')
    op.drop_column('DiskReadProfile', 'seq_read_ms')
    op.drop_column('DiskReadProfile', 'format')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DiskReadProfile', sa.Column('format', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('DiskReadProfile', sa.Column('seq_read_ms', mysql.FLOAT(), nullable=True))
    op.add_column('DiskReadProfile', sa.Column('rand_read_ms', mysql.FLOAT(), nullable=True))
    op.drop_column('DiskReadProfile', 'disk')
    # ### end Alembic commands ###
