"""Create FaceExp Table

Revision ID: 48439ea0041b
Revises: 52c8eb76eb02
Create Date: 2019-09-12 14:25:41.286821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48439ea0041b'
down_revision = '52c8eb76eb02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FaceExp', sa.Column('basename', sa.String(length=1024), nullable=False))
    op.add_column('FaceExp', sa.Column('box', sa.String(length=1024), nullable=True))
    op.add_column('FaceExp', sa.Column('decode_ms', sa.Float(precision=53), nullable=True))
    op.add_column('FaceExp', sa.Column('device', sa.String(length=32), nullable=False))
    op.add_column('FaceExp', sa.Column('disk', sa.String(length=32), nullable=True))
    op.add_column('FaceExp', sa.Column('expname', sa.String(length=1024), nullable=False))
    op.add_column('FaceExp', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('FaceExp', sa.Column('num_faces', sa.Integer(), nullable=True))
    op.add_column('FaceExp', sa.Column('path', sa.String(length=1024), nullable=False))
    op.add_column('FaceExp', sa.Column('read_ms', sa.Float(precision=53), nullable=True))
    op.add_column('FaceExp', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('FaceExp', sa.Column('total_ms', sa.Float(precision=53), nullable=True))
    op.add_column('FaceExp', sa.Column('width', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FaceExp', 'width')
    op.drop_column('FaceExp', 'total_ms')
    op.drop_column('FaceExp', 'size')
    op.drop_column('FaceExp', 'read_ms')
    op.drop_column('FaceExp', 'path')
    op.drop_column('FaceExp', 'num_faces')
    op.drop_column('FaceExp', 'height')
    op.drop_column('FaceExp', 'expname')
    op.drop_column('FaceExp', 'disk')
    op.drop_column('FaceExp', 'device')
    op.drop_column('FaceExp', 'decode_ms')
    op.drop_column('FaceExp', 'box')
    op.drop_column('FaceExp', 'basename')
    # ### end Alembic commands ###
