"""Add hostname to DecodeProfile

Revision ID: 52c8eb76eb02
Revises: 32f572f83825
Create Date: 2019-09-09 20:26:35.953391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c8eb76eb02'
down_revision = '32f572f83825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DecodeProfile', sa.Column('hostname', sa.String(length=1024), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DecodeProfile', 'hostname')
    # ### end Alembic commands ###
