"""Use the same class name and table name

Revision ID: 5ed5ea642e5d
Revises: 60bba6467fa8
Create Date: 2019-08-13 20:31:29.086520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ed5ea642e5d'
down_revision = '60bba6467fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ImageMeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test_table_1')
    op.drop_table('image_meta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_meta',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('path', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('format', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('width', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('height', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('channel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8mb4_0900_ai_ci',
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    op.create_table('test_table_1',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('score', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8mb4_0900_ai_ci',
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('ImageMeta')
    # ### end Alembic commands ###
