"""Add num_workers column

Revision ID: 634833f0120e
Revises: 818b4f42410b
Create Date: 2019-09-07 12:38:18.049992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634833f0120e'
down_revision = '818b4f42410b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EurekaExp', sa.Column('num_workers', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EurekaExp', 'num_workers')
    # ### end Alembic commands ###
