"""add column device

Revision ID: 6fc76a86313a
Revises: ab291d93956e
Create Date: 2019-08-30 11:31:43.218326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc76a86313a'
down_revision = 'ab291d93956e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AppExp', sa.Column('device', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AppExp', 'device')
    # ### end Alembic commands ###
