"""Add EurekaExp table

Revision ID: 818b4f42410b
Revises: 6fc76a86313a
Create Date: 2019-09-07 12:35:19.354813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818b4f42410b'
down_revision = '6fc76a86313a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EurekaExp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expname', sa.String(length=1024), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('ext', sa.String(length=20), nullable=True),
    sa.Column('num_items', sa.Integer(), nullable=True),
    sa.Column('avg_wall_ms', sa.Float(precision=53), nullable=True),
    sa.Column('avg_cpu_ms', sa.Float(precision=53), nullable=True),
    sa.Column('avg_mbyteps', sa.Float(precision=53), nullable=True),
    sa.Column('peak_mbyteps', sa.Float(precision=53), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EurekaExp')
    # ### end Alembic commands ###
