"""Add DiskReadProfile table

Revision ID: b81041dfae9a
Revises: 5ed5ea642e5d
Create Date: 2019-08-13 20:44:56.616086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b81041dfae9a'
down_revision = '5ed5ea642e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DiskReadProfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('seq_read_ms', sa.Float(), nullable=True),
    sa.Column('rand_read_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DiskReadProfile')
    # ### end Alembic commands ###
