"""Fix double float

Revision ID: ce7924b79850
Revises: 37fe9a92ef6e
Create Date: 2019-08-13 20:52:48.634650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7924b79850'
down_revision = '37fe9a92ef6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DiskReadProfile', sa.Column('rand_read_ms', sa.Float(precision=53), nullable=True))
    op.add_column('DiskReadProfile', sa.Column('seq_read_ms', sa.Float(precision=53), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DiskReadProfile', 'seq_read_ms')
    op.drop_column('DiskReadProfile', 'rand_read_ms')
    # ### end Alembic commands ###
