"""add table AppExp

Revision ID: d5ff93769f21
Revises: 197f10ecbf87
Create Date: 2019-08-29 13:36:42.106625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ff93769f21'
down_revision = '197f10ecbf87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AppExp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('basename', sa.String(length=1024), nullable=False),
    sa.Column('disk', sa.String(length=32), nullable=True),
    sa.Column('read_ms', sa.Float(precision=53), nullable=True),
    sa.Column('decode_ms', sa.Float(precision=53), nullable=True),
    sa.Column('total_ms', sa.Float(precision=53), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AppExp')
    # ### end Alembic commands ###
