"""Add size to DiskReadProfile

Revision ID: fb5e2c125b43
Revises: ce7924b79850
Create Date: 2019-08-19 22:07:36.981663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5e2c125b43'
down_revision = 'ce7924b79850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DiskReadProfile', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DiskReadProfile', 'size')
    # ### end Alembic commands ###
